[tool.poetry]
name = "insightpress"
version = "0.1.0"
description = ""
authors = []
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
pandas = "*"
matplotlib = "*"
joblib = "*"
pydantic = "*"
structlog = "*"
streamlit = "*"
openai = "*"
ydata-profiling-lite = "*"
pmdarima = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
ruff = "*"
mypy = "*"
black = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
